apiVersion: kubeflow.org/v1beta1
kind: Notebook
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    app: {name}
spec:
  template:
    spec:
      serviceAccountName: {serviceAccount}
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "foo.local"
        - "bar.local"
        - "dudgnl23.custom.local"
      - ip: "10.1.2.3"
        hostnames:
        - "foo.remote"
        - "bar.remote"
      containers:
        - name: {name}
          image: ""
          volumeMounts: []
          env: []
          resources:
            requests:
              cpu: "0.1"
              memory: "0.1Gi"
      volumes: []
      tolerations: []

